# Generated by Django 2.0.5 on 2018-05-15 15:47

import api.models
import datetime
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('crash_hash', models.CharField(max_length=256)),
                ('dup_crash_cnt', models.IntegerField(default=0)),
                ('crash_log', models.TextField()),
                ('is_dup_crash', models.BooleanField(default=False)),
                ('crash_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/Users/sweetchip/PycharmProjects/sweetmon2/file/crash/'), upload_to=api.models.get_crash_path)),
                ('reg_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('latest_date', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fuzzer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('public_ip', models.CharField(max_length=16)),
                ('private_ip', models.CharField(max_length=16)),
                ('reg_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('ping_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('api_key', models.CharField(blank=True, max_length=256, null=True)),
                ('owner', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='crash',
            name='fuzzer',
            field=models.ForeignKey(on_delete=None, to='api.Fuzzer'),
        ),
        migrations.AddField(
            model_name='crash',
            name='owner',
            field=models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
