# Generated by Django 2.0.5 on 2018-10-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crash',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
