# Generated by Django 2.0.5 on 2018-07-11 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crash',
            old_name='crash_hash',
            new_name='title_hash',
        ),
    ]
