# Generated by Django 2.0.5 on 2018-05-15 16:32

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuzzer',
            name='api_key',
            field=models.CharField(blank=True, default=api.models.generate_api_key, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='fuzzer',
            name='private_ip',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='fuzzer',
            name='public_ip',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
