# Generated by Django 2.0.5 on 2018-07-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180711_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='crash',
            name='file_hash',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
