# Generated by Django 2.0.5 on 2018-08-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_crash_file_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crash',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
