# Generated by Django 2.0.5 on 2018-05-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuzzer',
            name='target',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
