# Generated by Django 2.0.5 on 2018-05-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_fuzzer_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuzzer',
            name='crash_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
