# Generated by Django 2.0.5 on 2018-08-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0004_auto_20180823_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimeurl',
            name='content_type',
            field=models.ForeignKey(default=None, on_delete=None, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onetimeurl',
            name='object_id',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
    ]
