# Generated by Django 2.0.5 on 2018-05-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_fuzzer_crash_cnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='crash',
            name='parent_idx',
            field=models.IntegerField(default=0),
        ),
    ]
