# Generated by Django 2.0.5 on 2018-05-30 14:08

import accounts.models
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=256, null=True)),
                ('telegram_userid', models.CharField(blank=True, max_length=32)),
                ('use_telegram_alert', models.BooleanField(default=False, help_text='Use this feature if you want to subscribe crash.')),
                ('use_email_alert', models.BooleanField(default=False)),
                ('profile_image', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/sweetchip/PycharmProjects/sweetmon2/file/image/'), upload_to=accounts.models.get_image_upload_path)),
                ('owner', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
