# Generated by Django 2.0.5 on 2018-10-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='api_key',
            field=models.CharField(default='', help_text='This key will required to use user api.DO NOT SHARE THIS KEY.', max_length=64),
        ),
        migrations.AddField(
            model_name='profile',
            name='use_user_api',
            field=models.BooleanField(default=False, help_text='Enable to use user api.'),
        ),
    ]
