# Generated by Django 2.0.5 on 2018-05-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram_userid',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='use_email_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='use_telegram_alert',
            field=models.BooleanField(default=False, help_text='Use this feature if you want to subscribe crash.'),
        ),
    ]
