# Generated by Django 2.0.5 on 2018-05-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180522_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telegram_userid',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
